config/routes.rb
Rails.application.routes.draw do
  root to: 'post_codes#index'

  resources :post_codes, only: %i[create index]
end

app/models/allowed_list.rb
class AllowedList < ApplicationRecord
  validates :code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/post_codes_controller.rb
class PostCodesController < ApplicationController
  attr_reader :post_code

  helper_method :post_code

  def index; end

  def create
    respond_to do |format|
      format.js do
        validation = PostCodes::Validation.(permitted_params.to_h)

        @post_code = if validation.success?
                       PostCodes::Checker.new(permitted_params[:code]).call
                     else
                       PostCodes::Struct.new(permitted_params.to_h.symbolize_keys)
                     end
      end
    end
  end

  private

  def permitted_params
    params.require(:post_codes_form).permit(:code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_codes_helper.rb
module PostCodesHelper
  def decorate_validity(valid)
    valid ? 'allowed' : 'not allowed'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UkChallengeTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post_codes/create.js.erb
document.querySelector('#codeValidity').textContent = 'Post code <%= post_code.code %> is <%= decorate_validity(post_code.valid) %>'

app/views/post_codes/index.html.erb
<h1>
  Backend Engineer Coding Test
</h1>


<%= form_for PostCodes::Form.new, url: post_codes_path, remote: :true  do |f| %>
  <p> Enter post code </p>
  <%= f.text_field :code %>
  <%= f.submit('Submit') %>
<% end %>

<h3 id='codeValidity'></h3>